import json
import structlog
from pydantic import BaseModel, Field
from llm.factory import LLMFactory, ModelTier
from langchain_core.messages import SystemMessage, HumanMessage
from graph.state import InteractionState
from tools.neo4j_tools import fetch_neo4j_schema, execute_cypher

logger = structlog.get_logger(__name__)

class CypherQueryOutput(BaseModel):
    cypher: str = Field(description="The valid Cypher query to execute against Neo4j. Do not wrap in markdown or ```cypher.")

async def generate_cypher_node(state: InteractionState) -> dict:
    """
    Generates the Cypher query using the Neo4j schema.
    Applies the Reflexion pattern if an error_message exists.
    """
    logger.info("Generating Cypher", retries=state.get("retries", 0))
    
    schema = await fetch_neo4j_schema.ainvoke({})
    
    llm = LLMFactory.get_llm(tier=ModelTier.STANDARD)
    structured_llm = llm.with_structured_output(CypherQueryOutput)
    
    system_prompt = f"""You are a master Graph Data Engineer generating Cypher for Neo4j.
You must return ONLY the raw Cypher query.

{schema}

CRITICAL RULES:
1. Do NOT include '{{tenant_id: XYZ}}' in your MATCH clauses. The system will securely inject this for you.
2. If you see an 'Execution Error' below, you MUST fix your Cypher syntax based on that error.
"""
    
    user_msg = ""
    for msg in reversed(state.get("messages", [])):
        if isinstance(msg, HumanMessage):
            user_msg = msg.content
            break
            
    prompt_context = f"User Intent: {user_msg}\n"
    if state.get("error_message"):
        prompt_context += f"\nPREVIOUS EXECUTION ERROR:\n{state['error_message']}\n\nPlease fix your Cypher query."
        
    response = await structured_llm.ainvoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=prompt_context)
    ])
    
    return {"cypher_query": response.cypher}

async def execute_cypher_node(state: InteractionState) -> dict:
    """
    Executes the Cypher generated by the previous node.
    If it fails, increments retries and captures the error for Reflexion.
    """
    cypher_to_run = state.get("cypher_query", "")
    tenant_id = state.get("tenant_id", "default-tenant")
    logger.info("Executing Cypher", cypher=cypher_to_run)
    
    try:
        result = await execute_cypher.ainvoke({"query": cypher_to_run, "tenant_id": tenant_id})
        
        if "Cypher Error" in result or "Failed to" in result:
            logger.warning("Cypher Execution Failed", error=result)
            return {
                "error_message": result,
                "retries": 1,
            }

        user_msg = ""
        for msg in reversed(state.get("messages", [])):
            if isinstance(msg, HumanMessage):
                user_msg = msg.content
                break

        llm = LLMFactory.get_llm(tier=ModelTier.STANDARD)
        system_prompt = f"""You are an expert Knowledge Graph Analyst.
Answer the user's question based ONLY on the following Cypher query results.
Do not mention the Cypher query itself; summarize the relationships clearly.

<graph_results>
{result}
</graph_results>
"""
        response = await llm.ainvoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_msg)
        ])
            
        return {
            "error_message": "",
            "cypher_result": response.content,
            "references": [] 
        }
        
    except Exception as e:
        logger.error("Cypher Tool crashed", error=str(e))
        return {
            "error_message": str(e),
            "retries": 1,
        }
