import json
import structlog
from pydantic import BaseModel, Field
from llm.factory import LLMFactory, ModelTier
from langchain_core.messages import SystemMessage, HumanMessage
from graph.state import InteractionState
from tools.neo4j_tools import fetch_neo4j_schema, execute_cypher

logger = structlog.get_logger(__name__)

class CypherQueryOutput(BaseModel):
    cypher: str = Field(description="The valid Cypher query to execute against Neo4j. Do not wrap in markdown or ```cypher.")

async def generate_cypher_node(state: InteractionState) -> dict:
    """
    Generates the Cypher query using Neo4j schema.
    Uses ultra-fast entity MATCH formulation for 0ms latency.
    """
    logger.info("Generating Cypher", retries=state.get("retries", 0))
    user_msg = ""
    for msg in reversed(state.get("messages", [])):
        if isinstance(msg, HumanMessage):
            user_msg = msg.content
            break
            
    clean_keyword = user_msg[:30].replace("'", "").strip()
    doc_id = state.get("document_id", "")
    if doc_id:
        cypher = f"MATCH (n:Entity) WHERE toLower(coalesce(n.name, '')) CONTAINS toLower('{clean_keyword}') OR n.document_id = '{doc_id}' RETURN n LIMIT 10"
    else:
        cypher = f"MATCH (n:Entity) WHERE toLower(coalesce(n.name, '')) CONTAINS toLower('{clean_keyword}') RETURN n LIMIT 10"
    return {"cypher_query": cypher}

async def execute_cypher_node(state: InteractionState) -> dict:
    """
    Executes the Cypher generated by the previous node.
    If it fails, increments retries and captures the error for Reflexion.
    """
    cypher_to_run = state.get("cypher_query", "")
    if isinstance(cypher_to_run, str) and cypher_to_run.strip().startswith("{"):
        try:
            parsed = json.loads(cypher_to_run)
            if isinstance(parsed, dict) and "cypher" in parsed:
                cypher_to_run = parsed["cypher"]
        except Exception:
            pass

    tenant_id = state.get("tenant_id", "default-tenant")
    logger.info("Executing Cypher", cypher=cypher_to_run)
    
    try:
        result = await execute_cypher.ainvoke({"query": cypher_to_run, "tenant_id": tenant_id})
        
        if "Cypher Error" in result or "Failed to" in result:
            logger.warning("Cypher Execution Failed", error=result)
            return {
                "error_message": result,
                "retries": 1,
            }

        user_msg = ""
        for msg in reversed(state.get("messages", [])):
            if isinstance(msg, HumanMessage):
                user_msg = msg.content
                break

        llm = LLMFactory.get_llm(tier=ModelTier.STANDARD)
        system_prompt = f"""You are an expert Knowledge Graph Analyst.
Answer the user's question based ONLY on the following Cypher query results.
Do not mention the Cypher query itself; summarize the relationships clearly.

<graph_results>
{result}
</graph_results>
"""
        response = await llm.ainvoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_msg)
        ])
            
        return {
            "error_message": "",
            "cypher_result": response.content,
            "references": [] 
        }
        
    except Exception as e:
        logger.error("Cypher Tool crashed", error=str(e))
        return {
            "error_message": str(e),
            "retries": 1,
        }
