import json
import structlog
from typing import Optional
from pydantic import BaseModel, Field
from llm.factory import LLMFactory, ModelTier
from langchain_core.messages import SystemMessage, HumanMessage
from graph.state import InteractionState
from tools.neo4j_tools import fetch_neo4j_schema, execute_cypher
from graph.nodes.cypher_templates import CYPHER_TEMPLATES

logger = structlog.get_logger(__name__)

class CypherTemplateSelection(BaseModel):
    template_name: str = Field(description=f"Must be one of: {', '.join(CYPHER_TEMPLATES.keys())}")
    entity_name: str = Field(description="The core entity name extracted from the user query (e.g., 'Apple', 'Acme Corp').")
    reasoning: str = Field(description="Why this template was chosen.")

async def generate_cypher_node(state: InteractionState) -> dict:
    """
    Selects a Cypher template based on user intent.
    """
    logger.info("Generating Cypher via Templates", retries=state.get("retries", 0))
    user_msg = ""
    for msg in reversed(state.get("messages", [])):
        if isinstance(msg, HumanMessage):
            user_msg = msg.content
            break
            
    doc_id = state.get("document_id", "")
    
    from core.db import db_client
    tenant_id = state.get("tenant_id", "default-tenant")
    docs = await db_client.fetch_tenant_documents(tenant_id)
    doc_catalog = "\n".join([
        f"- [ID: {d['document_id']}] File: {d['filename']} | Company: {d.get('company_name')} ({d.get('ticker')}) | Period: {d.get('fiscal_period')}"
        for d in docs
    ])
    
    llm = LLMFactory.get_structured_llm(CypherTemplateSelection, ModelTier.FRONTIER)
    
    system_prompt = f"""You are a Knowledge Graph query router for Agentic Brain.
Map the user's question to the most appropriate Cypher template and extract the target entity name.

AVAILABLE TEMPLATES:
- FIND_SUBSIDIARIES: Use when asking about subsidiaries, child companies, or what a company owns.
- FIND_PARENT_COMPANY: Use when asking who owns a company or its parent.
- FIND_KEY_PERSONNEL: Use for finding CEOs, CFOs, Directors, or key management.
- FIND_AUDITORS: Use for finding the statutory auditors of a company.
- GENERAL_RELATIONSHIPS: Use for any other relationship mapping.

AVAILABLE DOCUMENTS IN KNOWLEDGE BASE:
{doc_catalog}

IMPORTANT RULES:
1. Extract the core `entity_name` strictly from the query (e.g., if they ask "who audits Apple", entity_name is "Apple").
2. Match it to one of the exact template names.
"""

    try:
        response = await llm.ainvoke([
            SystemMessage(content=system_prompt, additional_kwargs={"cache_control": {"type": "ephemeral"}}),
            HumanMessage(content=user_msg)
        ])
        
        template_name = response.template_name
        entity_name = response.entity_name or ""

        if (not entity_name or entity_name.lower() in ("the company", "company", "audit", "overview")) and docs:
            active_doc = next((d for d in docs if d.get("document_id") == doc_id), docs[0] if docs else None)
            if active_doc and active_doc.get("company_name"):
                entity_name = active_doc["company_name"]

        if not entity_name:
            entity_name = user_msg[:30].replace("'", "").strip()

        if template_name not in CYPHER_TEMPLATES:
            template_name = "GENERAL_RELATIONSHIPS"
            
        cypher = CYPHER_TEMPLATES[template_name]
        cypher = cypher.replace("$entity_name", f"'{entity_name}'")

    except Exception as e:
        logger.error("Cypher Template LLM failed", error=str(e))
        clean_keyword = user_msg[:30].replace("'", "").strip()
        cypher = CYPHER_TEMPLATES["GENERAL_RELATIONSHIPS"].replace("$entity_name", f"'{clean_keyword}'")

    return {"cypher_query": cypher}

async def execute_cypher_node(state: InteractionState) -> dict:
    """
    Executes the Cypher generated by the previous node.
    """
    cypher_to_run = state.get("cypher_query", "")
    tenant_id = state.get("tenant_id", "default-tenant")
    logger.info("Executing Cypher", cypher=cypher_to_run)
    
    try:
        result = await execute_cypher.ainvoke({"query": cypher_to_run, "tenant_id": tenant_id})
        
        if "Cypher Error" in result or "Failed to" in result:
            logger.warning("Cypher Execution Failed", error=result)
            return {
                "error_message": result,
                "retries": 1,
            }

        return {
            "error_message": "",
            "cypher_result": result,
            "references": [] 
        }
        
    except Exception as e:
        logger.error("Cypher Tool crashed", error=str(e))
        return {
            "error_message": str(e),
            "retries": 1,
        }
