cubes:
- name: ViewReceiptLineItems
  sql: SELECT * FROM view_receipt_line_items
  measures:
  - name: count
    type: count
  - name: total_quantity
    type: sum
    sql: quantity
  - name: avg_quantity
    type: avg
    sql: quantity
  - name: sum_price
    type: sum
    sql: price
  - name: avg_price
    type: avg
    sql: price
  - name: total_discount
    type: sum
    sql: discount
  - name: avg_discount
    type: avg
    sql: discount
  - name: total_total_price
    type: sum
    sql: total_price
  - name: avg_total_price
    type: avg
    sql: total_price
  dimensions:
  - name: id
    type: string
    sql: id
    primary_key: true
  - name: tenant_id
    type: string
    sql: tenant_id
  - name: sys_document_id
    type: string
    sql: sys_document_id
  - name: item_code
    type: string
    sql: item_code
  - name: item_description
    type: string
    sql: item_description
  - name: quantity
    type: number
    sql: quantity
  - name: price
    type: number
    sql: price
  - name: discount
    type: number
    sql: discount
  - name: total_price
    type: number
    sql: total_price
  - name: tax_indicator
    type: string
    sql: tax_indicator
  - name: additional_metadata
    type: string
    sql: CAST(additional_metadata AS TEXT)
